
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chathura
 */
public class Admin_Home extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Home
     */
    public Admin_Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_time = new javax.swing.JLabel();
        date_txt = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        txt_teacher_management = new rojerusan.RSLabelImage();
        jLabel2 = new rojerusan.RSLabelImage();
        txt_Employee = new javax.swing.JButton();
        txt_teachers = new javax.swing.JButton();
        txt_teachers1 = new javax.swing.JButton();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin_Home");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_time.setText("Time:");
        jPanel1.add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        date_txt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date_txt.setText("Current Date:");
        jPanel1.add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 190, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sbg.png"))); // NOI18N
        jPanel1.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 300, 230));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/—Pngtree—beauty teacher beauty teacher beautiful_3933231.png"))); // NOI18N
        jPanel1.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 130));

        txt_teacher_management.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/—Pngtree—happy jumping friends office workers_5435920.png"))); // NOI18N
        jPanel1.add(txt_teacher_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 130, 130));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png-employee-avoid-condescension-and-treat-employees-with-respect-no-adult-wants-to-be-micromanaged-and-have-their-hand-held-throughout-the-day-258.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 140, 140, 120));

        txt_Employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Employee.setText("All Employees");
        txt_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 280, 130, -1));

        txt_teachers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teachers.setText("All Students");
        txt_teachers.setToolTipText("Teachers Data Entry Option");
        txt_teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachersActionPerformed(evt);
            }
        });
        jPanel1.add(txt_teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 280, 120, -1));

        txt_teachers1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teachers1.setText("All Teachers");
        txt_teachers1.setToolTipText("Teachers Data Entry Option");
        txt_teachers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachers1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_teachers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wave.png"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
 private JFrame frame1;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        frame1 = new JFrame("Logout");
        if (JOptionPane.showConfirmDialog(frame1,"Confirm if you want to Logout","Home",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        this.dispose();//to close the current jframe
       new Admin().setVisible(true);
        };
    }//GEN-LAST:event_jLabel3MouseClicked

    private void txt_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeActionPerformed
        // TODO add your handling code here:
        All_Employees_Data_Details s = new All_Employees_Data_Details();
        s.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_txt_EmployeeActionPerformed

    private void txt_teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachersActionPerformed
        // TODO add your handling code here:
        All_Students_Data_Details ob = new All_Students_Data_Details();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txt_teachersActionPerformed

    private void txt_teachers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachers1ActionPerformed
        // TODO add your handling code here:
        All_Teachers_data_details ob = new All_Teachers_data_details();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txt_teachers1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_txt;
    private rojerusan.RSLabelImage jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelImage rSLabelImage3;
    private javax.swing.JButton txt_Employee;
    private rojerusan.RSLabelImage txt_teacher_management;
    private javax.swing.JButton txt_teachers;
    private javax.swing.JButton txt_teachers1;
    private javax.swing.JLabel txt_time;
    // End of variables declaration//GEN-END:variables
}
