
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Employees_Infromation_System extends javax.swing.JFrame {

    /**
     * Creates new form Employees_Infromation_System
     */
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Employees_Infromation_System() {
        initComponents();
       conn=javaconnect.connerDb();
       CurrentDate();
    }
    
        public  void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
    
        
          public void CurrentDate() 
    {

        
        Thread clock=new Thread()
        {
            public void run()
            {
                for(;;)
                    
                {
                
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        
        txt_date.setText(day+"/"+(month+1)+"/"+(year));
        
        
        
        int second=cal.get(Calendar.SECOND); 
        int mint=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR);
        txt_time.setText(hour+":"+(mint)+":"+(second));  
        

                    
                    try {
                        sleep(1000);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Students_and_Teachers_Management.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        
        
        
        clock.start();
        
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txt_date = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_present = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_permanent = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_texit = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cmd_tdelete = new javax.swing.JButton();
        txt_tclear = new javax.swing.JButton();
        txt_tupdate = new javax.swing.JButton();
        cmd_tsave = new javax.swing.JButton();
        txt_lastname = new javax.swing.JTextField();
        txt_position = new javax.swing.JTextField();
        txt_birthday = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_mobile = new javax.swing.JTextField();
        txt_sex = new javax.swing.JTextField();
        txt_firstname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txt_teacher_ID = new javax.swing.JTextField();
        cmd_search = new javax.swing.JTextField();
        txt_time = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Employee's Information System");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_date.setText("Date");
        jPanel2.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 520, 180, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 51, 153));
        jLabel14.setText("Search here");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee's ID");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 130, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Position:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Birth Day:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mobile No:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Sex:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Permanent Address:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Present Address:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, -1, -1));

        txt_present.setToolTipText("Enter Present Address");
        txt_present.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_presentActionPerformed(evt);
            }
        });
        jPanel2.add(txt_present, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 116, -1));

        jLabel25.setText("Max: 30 Digits");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, -1, -1));

        jLabel24.setText("Max: 30 Digits");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, -1, -1));

        txt_permanent.setToolTipText("Enter Permanent Address");
        jPanel2.add(txt_permanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 116, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel5.setText("Ex: male,female");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 380, -1, 20));

        txt_texit.setBackground(new java.awt.Color(255, 255, 255));
        txt_texit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_texit.setForeground(new java.awt.Color(255, 51, 51));
        txt_texit.setText("Exit");
        txt_texit.setToolTipText("Exit from The program");
        txt_texit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_texitActionPerformed(evt);
            }
        });
        jPanel2.add(txt_texit, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 95, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 51, 255));
        jButton1.setText("View Data");
        jButton1.setToolTipText("View All The Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 320, -1, -1));

        cmd_tdelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_tdelete.setForeground(new java.awt.Color(255, 0, 102));
        cmd_tdelete.setText("Delete");
        cmd_tdelete.setToolTipText("Delete The Selected Data");
        cmd_tdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_tdeleteActionPerformed(evt);
            }
        });
        jPanel2.add(cmd_tdelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, 95, -1));

        txt_tclear.setBackground(new java.awt.Color(255, 255, 255));
        txt_tclear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tclear.setForeground(new java.awt.Color(153, 0, 153));
        txt_tclear.setText("Clear");
        txt_tclear.setToolTipText("Clear Data");
        txt_tclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tclearActionPerformed(evt);
            }
        });
        jPanel2.add(txt_tclear, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 240, 95, -1));

        txt_tupdate.setBackground(new java.awt.Color(255, 255, 255));
        txt_tupdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txt_tupdate.setForeground(new java.awt.Color(204, 51, 0));
        txt_tupdate.setText("Update");
        txt_tupdate.setToolTipText("Update The Selected Data");
        txt_tupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tupdateActionPerformed(evt);
            }
        });
        jPanel2.add(txt_tupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 95, -1));

        cmd_tsave.setBackground(new java.awt.Color(255, 255, 255));
        cmd_tsave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_tsave.setForeground(new java.awt.Color(51, 0, 51));
        cmd_tsave.setText("Save Data");
        cmd_tsave.setToolTipText("Save all the input data");
        cmd_tsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_tsaveActionPerformed(evt);
            }
        });
        jPanel2.add(cmd_tsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, -1, -1));

        txt_lastname.setToolTipText("Enter last name");
        jPanel2.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 116, -1));

        txt_position.setToolTipText("Enter Junior senior ");
        jPanel2.add(txt_position, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 240, 116, -1));

        txt_birthday.setToolTipText("Enter BOD: yyyy-mm-dd");
        txt_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_birthdayActionPerformed(evt);
            }
        });
        jPanel2.add(txt_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 116, -1));

        jLabel22.setText("Ex: yyyy-mm-dd");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 300, -1, 20));

        txt_mobile.setToolTipText("Enter Your Mobile Number");
        jPanel2.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 320, 116, -1));

        txt_sex.setToolTipText("male,famale");
        jPanel2.add(txt_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 116, -1));

        txt_firstname.setToolTipText("Enter First Name");
        jPanel2.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 116, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("Four Digits Only");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 150, -1, 20));

        txt_teacher_ID.setToolTipText("Enter Six Digit ID number");
        txt_teacher_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teacher_IDActionPerformed(evt);
            }
        });
        jPanel2.add(txt_teacher_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 116, -1));

        cmd_search.setBackground(new java.awt.Color(255, 204, 204));
        cmd_search.setForeground(new java.awt.Color(255, 51, 51));
        cmd_search.setToolTipText("Search The Entry Data");
        cmd_search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cmd_search.setSelectedTextColor(new java.awt.Color(0, 153, 153));
        cmd_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_searchActionPerformed(evt);
            }
        });
        jPanel2.add(cmd_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 112, -1));

        txt_time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_time.setText("Time");
        jPanel2.add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 30));

        jButton3.setBackground(new java.awt.Color(50, 190, 143));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Home");
        jButton3.setToolTipText("Back To The Main Manu");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, -1));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/authentication.png"))); // NOI18N
        jPanel2.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 310, 250));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wave.png"))); // NOI18N
        jPanel2.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 560));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1140, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        Students_and_Teachers_Management e = new Students_and_Teachers_Management();
        e.setVisible(true);
        close();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_texitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_texitActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_txt_texitActionPerformed

    private void txt_tclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tclearActionPerformed
        // TODO add your handling code here:
//        int p=JOptionPane.showConfirmDialog(null, "Do you Want to Clear Data?","Clear",JOptionPane.YES_NO_OPTION);
//        if(p==0)
//        {
        
        cmd_search.setText("");
        txt_teacher_ID.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_position.setText("");
        txt_birthday.setText("");
        txt_mobile.setText("");
        txt_sex.setText("");
        txt_permanent.setText("");
        txt_present.setText("");
        
//         JOptionPane.showMessageDialog(null, "Data field Clear.");
//        }
    }//GEN-LAST:event_txt_tclearActionPerformed

    private void txt_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_birthdayActionPerformed

    private void cmd_tdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_tdeleteActionPerformed
        // TODO add your handling code here:

        int p=JOptionPane.showConfirmDialog(null, "Are you Sure to Delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            String sql="delete from employee_info where Employee_id=?";
            try {
                pst=conn.prepareStatement(sql);

                pst.setString(1, txt_teacher_ID.getText());

                pst.execute();

                JOptionPane.showMessageDialog(null, "Data Deleted Successfully.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null,"We face a Problem.");
            }

        }
    }//GEN-LAST:event_cmd_tdeleteActionPerformed

    private void cmd_tsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_tsaveActionPerformed
        // TODO add your handling code here:

        int p=JOptionPane.showConfirmDialog(null, "Are you Sure to Save?","Save",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            try {

                String sql="insert into employee_info (Employee_id,First_name,Last_name,Position,Birth_day,Mobile_no,Sex,Permanent,Present) values(?,?,?,?,?,?,?,?,?)";

                pst=conn.prepareStatement(sql);

                pst.setString(1, txt_teacher_ID.getText());
                pst.setString(2, txt_firstname.getText());
                pst.setString(3, txt_lastname.getText());
                pst.setString(4, txt_position.getText());
                pst.setString(5, txt_birthday.getText());
                pst.setString(6, txt_mobile.getText());
                pst.setString(7, txt_sex.getText());
                pst.setString(8, txt_permanent.getText());
                pst.setString(9, txt_present.getText());

                pst.execute();
                JOptionPane.showMessageDialog(null, "Data Saved Successfully.");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "We face a Problem.");
            }

        }
    }//GEN-LAST:event_cmd_tsaveActionPerformed

    private void txt_tupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tupdateActionPerformed
        // TODO add your handling code here:

        int p=JOptionPane.showConfirmDialog(null, "Are you Sure to Update?","Update",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
            try {

                String value1=txt_teacher_ID.getText();
                String value2=txt_firstname.getText();
                String value3=txt_lastname.getText();
                String value4=txt_position.getText();
                String value6=txt_birthday.getText();
                String value7=txt_mobile.getText();
                String value8=txt_sex.getText();
                String value9=txt_permanent.getText();
                String value10=txt_present.getText();

                String sql="Update employee_info set Employee_id='"+value1+"',First_name='"+value2+"',Last_name='"+value3+"',Position='"+value4+"',Birth_day='"+value6+"',Mobile_no='"+value7+"',Sex='"+value8+"',permanent='"+value9+"',Present='"+value10+"' where Employee_id='"+value1+"'";

                pst=conn.prepareStatement(sql);
                pst.execute();

                JOptionPane.showMessageDialog(null,"Table Updated Successfully.");

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null,"We face a Problem.");
            }
        }

    }//GEN-LAST:event_txt_tupdateActionPerformed

    private void txt_presentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_presentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_presentActionPerformed

    private void txt_teacher_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teacher_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_teacher_IDActionPerformed

    private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_searchActionPerformed
        // TODO add your handling code here:

        try {
            String sql="select  * from  employee_info where Employee_id=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
            
            else 
            {
                  JOptionPane.showMessageDialog(null,"No data Found.Please try again!!!");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        
        
                try {
            String sql="select  * from  employee_info where First_name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        
                 try {
            String sql="select  * from  employee_info where Last_name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        
         try {
            String sql="select  * from  employee_info where Position=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        
         
          try {
            String sql="select  * from  employee_info where Birth_day=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        
           try {
            String sql="select  * from  employee_info where Mobile_no=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        

            try {
            String sql="select  * from  employee_info where Sex=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        
             try {
            String sql="select  * from  employee_info where Permanent=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
         try {
            String sql="select  * from  employee_info where Present=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Employee_id");
                txt_teacher_ID.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Position");
                txt_position.setText(add4);

                String add5=rs.getString("Birth_day");
                txt_birthday.setText(add5);

                String add6=rs.getString("Mobile_no");
                txt_mobile.setText(add6);

                String add7=rs.getString("Sex");
                txt_sex.setText(add7);

                String add8=rs.getString("Permanent");
                txt_permanent.setText(add8);

                String add9=rs.getString("Present");
                txt_present.setText(add9);

            }
 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }
        
            
    }//GEN-LAST:event_cmd_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        All_Employees_Data_Details e = new All_Employees_Data_Details();
        e.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employees_Infromation_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employees_Infromation_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employees_Infromation_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employees_Infromation_System.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employees_Infromation_System().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cmd_search;
    private javax.swing.JButton cmd_tdelete;
    private javax.swing.JButton cmd_tsave;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private javax.swing.JTextField txt_birthday;
    private javax.swing.JLabel txt_date;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_permanent;
    private javax.swing.JTextField txt_position;
    private javax.swing.JTextField txt_present;
    private javax.swing.JTextField txt_sex;
    private javax.swing.JButton txt_tclear;
    private javax.swing.JTextField txt_teacher_ID;
    private javax.swing.JButton txt_texit;
    private javax.swing.JLabel txt_time;
    private javax.swing.JButton txt_tupdate;
    // End of variables declaration//GEN-END:variables
}
