
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Students_and_Teachers_Management extends javax.swing.JFrame {

    /**
     * Creates new form Students_and_Teachers_Management
     */
    
     
            
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Students_and_Teachers_Management() {
        initComponents();
        
                
        conn=javaconnect.connerDb();
        CurrentDate();
    }
    
    
        
    public void CurrentDate() 
    {

        
        Thread clock=new Thread()
        {
            public void run()
            {
                for(;;)
                    
                {
                
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        
        date_txt.setText(day+"/"+(month+1)+"/"+(year));
        
        
        
        int second=cal.get(Calendar.SECOND); 
        int mint=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR);
        txt_time.setText(hour+":"+(mint)+":"+(second));  
        

                    
                    try {
                        sleep(1000);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Students_and_Teachers_Management.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        
        
        
        clock.start();
        
                
    }
    
        
    public  void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        date_txt = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        txt_teachers = new javax.swing.JButton();
        txt_Employee = new javax.swing.JButton();
        txt_teachers1 = new javax.swing.JButton();
        txt_teacher_management = new rojerusan.RSLabelImage();
        rSLabelImage3 = new rojerusan.RSLabelImage();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new rojerusan.RSLabelImage();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Information");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        date_txt.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        date_txt.setText("Current Date:");
        jPanel1.add(date_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 440, 190, 40));

        txt_time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_time.setText("Time:");
        jPanel1.add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, -1));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/—Pngtree—beauty teacher beauty teacher beautiful_3933231.png"))); // NOI18N
        jPanel1.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 130, 150, 130));

        txt_teachers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teachers.setText("Students");
        txt_teachers.setToolTipText("Teachers Data Entry Option");
        txt_teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachersActionPerformed(evt);
            }
        });
        jPanel1.add(txt_teachers, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 280, 100, -1));

        txt_Employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Employee.setText("Employees");
        txt_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeActionPerformed(evt);
            }
        });
        jPanel1.add(txt_Employee, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 280, 120, -1));

        txt_teachers1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teachers1.setText("Teachers");
        txt_teachers1.setToolTipText("Teachers Data Entry Option");
        txt_teachers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachers1ActionPerformed(evt);
            }
        });
        jPanel1.add(txt_teachers1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, -1, -1));

        txt_teacher_management.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/—Pngtree—happy jumping friends office workers_5435920.png"))); // NOI18N
        jPanel1.add(txt_teacher_management, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 130, 130));

        rSLabelImage3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sbg.png"))); // NOI18N
        jPanel1.add(rSLabelImage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 300, 230));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Logout");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 10, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/png-employee-avoid-condescension-and-treat-employees-with-respect-no-adult-wants-to-be-micromanaged-and-have-their-hand-held-throughout-the-day-258.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 140, 140, 120));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wave.png"))); // NOI18N
        jPanel1.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 490));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachersActionPerformed
        // TODO add your handling code here:
        Students_Infromation ob = new Students_Infromation();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txt_teachersActionPerformed

    private void txt_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeActionPerformed
        // TODO add your handling code here:
                 Employees_Infromation_System s = new Employees_Infromation_System();
                 s.setVisible(true);
                 close();
        
    }//GEN-LAST:event_txt_EmployeeActionPerformed

    private void txt_teachers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachers1ActionPerformed
        // TODO add your handling code here:
        Teachers_Information_System ob = new Teachers_Information_System();
        ob.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txt_teachers1ActionPerformed
private JFrame frame1;
    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        frame1 = new JFrame("Logout");
        if (JOptionPane.showConfirmDialog(frame1,"Confirm if you want to Logout","Home",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION){
        this.dispose();//to close the current jframe
        new Login_frame().setVisible(true);
        };
    }//GEN-LAST:event_jLabel3MouseClicked

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private rojerusan.RSLabelImage jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private rojerusan.RSLabelImage rSLabelImage3;
    private javax.swing.JButton txt_Employee;
    private rojerusan.RSLabelImage txt_teacher_management;
    private javax.swing.JButton txt_teachers;
    private javax.swing.JButton txt_teachers1;
    private javax.swing.JLabel txt_time;
    // End of variables declaration//GEN-END:variables
}
