
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.text.*;
import java.awt.print.*;
import static java.lang.Thread.sleep;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Students_Infromation extends javax.swing.JFrame {

        
    
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    
    /**
     * Creates new form Students_Infromation_System
     */
    public Students_Infromation() {
        initComponents();
        conn=javaconnect.connerDb();
         CurrentDate();
        
    }
    
     
        public  void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }
        
                
    public void CurrentDate() 
    {

        
        Thread clock=new Thread()
        {
            public void run()
            {
                for(;;)
                    
                {
                
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
        int year=cal.get(Calendar.YEAR);
        int day=cal.get(Calendar.DAY_OF_MONTH);
        
        txt_date.setText(day+"/"+(month+1)+"/"+(year));
        
        
        
        int second=cal.get(Calendar.SECOND); 
        int mint=cal.get(Calendar.MINUTE);
        int hour=cal.get(Calendar.HOUR);
        txt_time.setText(hour+":"+(mint)+":"+(second));  
        

                    
                    try {
                        sleep(1000);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Students_and_Teachers_Management.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        };
        
        
        
        clock.start();
        
                
    }
    
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        jMenu12 = new javax.swing.JMenu();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        cmd_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_roll = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_firstname = new javax.swing.JTextField();
        txt_lastname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_classname = new javax.swing.JTextField();
        cmd_save = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txt_present = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_permanent = new javax.swing.JTextField();
        txt_sex = new javax.swing.JTextField();
        txt_mobile = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        txt_birthday = new javax.swing.JTextField();
        txt_year = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_home = new javax.swing.JButton();
        txt_date = new javax.swing.JLabel();
        txt_time = new javax.swing.JLabel();
        rSLabelImage2 = new rojerusan.RSLabelImage();
        rSLabelImage1 = new rojerusan.RSLabelImage();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar4.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar4.add(jMenu9);

        jMenu10.setText("jMenu10");

        jMenu11.setText("File");
        jMenuBar5.add(jMenu11);

        jMenu12.setText("Edit");
        jMenuBar5.add(jMenu12);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("School Management System");
        setMaximumSize(new java.awt.Dimension(1128, 539));
        setMinimumSize(new java.awt.Dimension(1128, 539));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 102, 0));
        jLabel14.setText("Search here");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        cmd_search.setBackground(new java.awt.Color(255, 204, 204));
        cmd_search.setForeground(new java.awt.Color(255, 51, 51));
        cmd_search.setToolTipText("Search Entry Data");
        cmd_search.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        cmd_search.setSelectedTextColor(new java.awt.Color(0, 153, 153));
        cmd_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_searchActionPerformed(evt);
            }
        });
        jPanel3.add(cmd_search, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, 112, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Class Roll Number:");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        txt_roll.setToolTipText("Enter Five Digit Class Roll Number");
        txt_roll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_rollActionPerformed(evt);
            }
        });
        jPanel3.add(txt_roll, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 116, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel20.setText("Five Digits Only");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 70, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, -1, -1));

        txt_firstname.setToolTipText("Enter First Name");
        jPanel3.add(txt_firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 116, -1));

        txt_lastname.setToolTipText("Enter Last Name");
        jPanel3.add(txt_lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 170, 116, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Class:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        txt_classname.setToolTipText("Enter Class:6,7,8,9,10");
        jPanel3.add(txt_classname, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 210, 116, -1));

        cmd_save.setBackground(new java.awt.Color(255, 255, 255));
        cmd_save.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_save.setForeground(new java.awt.Color(102, 102, 255));
        cmd_save.setText("Save Data");
        cmd_save.setToolTipText("Save all the input data");
        cmd_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_saveActionPerformed(evt);
            }
        });
        jPanel3.add(cmd_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 170, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 0, 51));
        jButton2.setText("Update");
        jButton2.setToolTipText("Update The Selected Data");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 210, 95, -1));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 153));
        jButton3.setText("Clear");
        jButton3.setToolTipText("Clear Data");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 250, 95, -1));

        cmd_delete.setBackground(new java.awt.Color(255, 255, 255));
        cmd_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_delete.setForeground(new java.awt.Color(0, 51, 51));
        cmd_delete.setText("Delete");
        cmd_delete.setToolTipText("Delete The Selected Data");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });
        jPanel3.add(cmd_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 280, 95, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("View Data");
        jButton1.setToolTipText("View All The Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 330, -1, -1));

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 51, 51));
        jButton5.setText("Exit");
        jButton5.setToolTipText("Exit from The program");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 360, 95, -1));

        jLabel23.setText("Max: 30 Digits");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, -1, -1));

        jLabel24.setText("Max: 30 Digits");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 440, -1, -1));

        txt_present.setToolTipText("Your Present Address");
        txt_present.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_presentActionPerformed(evt);
            }
        });
        jPanel3.add(txt_present, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 116, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Present Address:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Permanent Address:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 400, -1, -1));

        txt_permanent.setToolTipText("Your Permanent Address");
        jPanel3.add(txt_permanent, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 400, 116, -1));

        txt_sex.setToolTipText("male,female");
        jPanel3.add(txt_sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 360, 116, -1));

        txt_mobile.setToolTipText("Enter Your Mobile Number");
        jPanel3.add(txt_mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 330, 116, -1));

        jLabel22.setText("Ex: yyyy-mm-dd");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 304, -1, 20));

        txt_birthday.setToolTipText("Enter BOD:yyyy-mm-dd");
        txt_birthday.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_birthdayActionPerformed(evt);
            }
        });
        jPanel3.add(txt_birthday, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 280, 116, -1));

        txt_year.setToolTipText("Academic Year");
        jPanel3.add(txt_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 116, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel21.setText("EX: 6,7,8,9,10");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 230, 60, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Year:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Birth Day:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mobile No:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Sex:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        txt_home.setBackground(new java.awt.Color(50, 190, 143));
        txt_home.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_home.setText("Home");
        txt_home.setToolTipText("Back to Home Manu");
        txt_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_homeActionPerformed(evt);
            }
        });
        jPanel3.add(txt_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 0, -1, -1));

        txt_date.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_date.setText("Date");
        jPanel3.add(txt_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 490, 180, -1));

        txt_time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txt_time.setText("Time");
        jPanel3.add(txt_time, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 170, -1));

        rSLabelImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/log.png"))); // NOI18N
        jPanel3.add(rSLabelImage2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 260, 230));

        rSLabelImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wave.png"))); // NOI18N
        jPanel3.add(rSLabelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 540));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmd_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_searchActionPerformed
        // TODO add your handling code here:

        try {
            String sql="select  * from  student_info where Roll=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }
            
        else 
            {
                  JOptionPane.showMessageDialog(null,"No data Found.Please try again!!!");
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where First_name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where Last_name=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);

        }

        try {
            String sql="select  * from  student_info where Class=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where Year=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where Birth_date=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where Mobile_no=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where Sex=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where permanent=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"We face a Problem.");

        }

        try {
            String sql="select  * from  student_info where Present=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, cmd_search.getText());

            rs=pst.executeQuery();

            if(rs.next())
            {

                String add1=rs.getString("Roll");
                txt_roll.setText(add1);

                String add2=rs.getString("First_name");
                txt_firstname.setText(add2);

                String add3=rs.getString("Last_name");
                txt_lastname.setText(add3);

                String add4=rs.getString("Class");
                txt_classname.setText(add4);

                String add5=rs.getString("Year");
                txt_year.setText(add5);

                String add6=rs.getString("Birth_date");
                txt_birthday.setText(add6);

                String add7=rs.getString("Mobile_no");
                txt_mobile.setText(add7);

                String add8=rs.getString("Sex");
                txt_sex.setText(add8);

                String add9=rs.getString("permanent");
                txt_permanent.setText(add9);

                String add10=rs.getString("Present");
                txt_present.setText(add10);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e);

        }

    }//GEN-LAST:event_cmd_searchActionPerformed

    private void txt_presentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_presentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_presentActionPerformed

    private void cmd_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_saveActionPerformed
        // TODO add your handling code here:
        
        int p=JOptionPane.showConfirmDialog(null, "Are you Sure to Save?","Save",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        try {

            String sql="insert into student_info (Roll,First_name,Last_name,Class,Year,Birth_date,Mobile_no,Sex,permanent,Present) values(?,?,?,?,?,?,?,?,?,?)";

            pst=conn.prepareStatement(sql);

            pst.setString(1, txt_roll.getText());
            pst.setString(2, txt_firstname.getText());
            pst.setString(3, txt_lastname.getText());
            pst.setString(4, txt_classname.getText());
            pst.setString(5, txt_year.getText());
            pst.setString(6, txt_birthday.getText());
            pst.setString(7, txt_mobile.getText());
            pst.setString(8, txt_sex.getText());
            pst.setString(9, txt_permanent.getText());
            pst.setString(10, txt_present.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Save Successfully.");

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, e);
        }
        }
        
     

    }//GEN-LAST:event_cmd_saveActionPerformed

    private void txt_birthdayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_birthdayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_birthdayActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        cmd_search.setText("");
        txt_roll.setText("");
        txt_firstname.setText("");
        txt_lastname.setText("");
        txt_classname.setText("");
        txt_year.setText("");
        txt_birthday.setText("");
        txt_mobile.setText("");
        txt_sex.setText("");
        txt_permanent.setText("");
        txt_present.setText("");

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        close();

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                
        int p=JOptionPane.showConfirmDialog(null, "Are you Sure to Update data?","Update",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
           try {
            
            String value1=txt_roll.getText();
            String value2=txt_firstname.getText();  
            String value3=txt_lastname.getText();
            String value4=txt_classname.getText();
            String value5=txt_year.getText();
            String value6=txt_birthday.getText();
            String value7=txt_mobile.getText();
            String value8=txt_sex.getText();
            String value9=txt_permanent.getText();
            String value10=txt_present.getText();
            
            String sql="Update student_info set Roll='"+value1+"',First_name='"+value2+"',Last_name='"+value3+"',Class='"+value4+"', Year='"+value5+"',Birth_date='"+value6+"',Mobile_no='"+value7+"',Sex='"+value8+"',permanent='"+value9+"',Present='"+value10+"' where Roll='"+value1+"'";        
            
            
            
            pst=conn.prepareStatement(sql);
             pst.execute();
            
           JOptionPane.showMessageDialog(null,"Table Updated Successfully."); 
            
        } catch (Exception e) {
              
            JOptionPane.showMessageDialog(null,"We face a Problem."); 
        }
        
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed
        // TODO add your handling code here:
             //   Admin e = new Admin();
              //  e.setVisible(true);
                
        int p=JOptionPane.showConfirmDialog(null, "Are you Sure to Delete?","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0)
        {
        String sql="delete from student_info where Roll=?";
        try {
            pst=conn.prepareStatement(sql);
            
            pst.setString(1, txt_roll.getText());

            pst.execute();

             JOptionPane.showMessageDialog(null, "Data Deleted Successfully"); 
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null,"We face a Problem."); 
        }
        }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void txt_rollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_rollActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txt_rollActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
                All_Students_Data_Details e = new All_Students_Data_Details();
                e.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_homeActionPerformed
        // TODO add your handling code here:
                
                Students_and_Teachers_Management e = new Students_and_Teachers_Management();
                e.setVisible(true);
                close();
        
    }//GEN-LAST:event_txt_homeActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmd_delete;
    private javax.swing.JButton cmd_save;
    private javax.swing.JTextField cmd_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JPanel jPanel3;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private rojerusan.RSLabelImage rSLabelImage1;
    private rojerusan.RSLabelImage rSLabelImage2;
    private javax.swing.JTextField txt_birthday;
    private javax.swing.JTextField txt_classname;
    private javax.swing.JLabel txt_date;
    private javax.swing.JTextField txt_firstname;
    private javax.swing.JButton txt_home;
    private javax.swing.JTextField txt_lastname;
    private javax.swing.JTextField txt_mobile;
    private javax.swing.JTextField txt_permanent;
    private javax.swing.JTextField txt_present;
    private javax.swing.JTextField txt_roll;
    private javax.swing.JTextField txt_sex;
    private javax.swing.JLabel txt_time;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
